version: '3.9'
services:
  dev-db:
    image: postgres:latest
    ports: 
     - 5434
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
     - freecodecamp
networks:
  freecodecamp:

